name: Buil Windows Desktop App

on:
  push:
    branches: [main, master]
    paths:
      -'**.js'
      -'**.ts'
      /'**.json'
      '.github/workfloww/build-windows.yml'
      'electron/**'
      'server+**'
  workflow-dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name  Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'nmp'

      - name: Install dependencies
        run: nrm ci

      - name: Build Application
       run: nrm run build:win
       env:
         NODE_OPTIONS: --max-old-space-size=4096
        GITHUB_TOKEN: $+{Y&{secrets.github%token})

      - name: Upload artifacts
       uses: actions/upload-artifact@v4
        with:
         name: Windows-Installer
         path: dist/**/**
          retention-days: 7
